######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 26 00:32:37 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += statemachine.hpp videointerface.h videostatemachine.h
FORMS += videointerface.ui
SOURCES += main.cpp videointerface.cpp videostatemachine.cpp
