######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 16 22:49:41 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += statemachine.hpp videointerface.h \
    videostatemachine.h
FORMS += videointerface.ui
SOURCES += main.cpp videointerface.cpp \
    videostatemachine.cpp
