######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 26 00:34:37 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += StateMachine.h videointerface.h videostatemachine.h
FORMS += videointerface.ui
SOURCES += main.cpp StateMachine.cpp videointerface.cpp videostatemachine.cpp
